# Generated by Django 3.2.4 on 2021-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Место')),
                ('time', models.CharField(max_length=10, verbose_name='Время добавления')),
                ('notes', models.TextField(verbose_name='Заметки для места ')),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'verbose_name': 'Осенняя локация',
                'verbose_name_plural': 'Осении локации',
            },
        ),
        migrations.CreateModel(
            name='spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Место')),
                ('time', models.CharField(max_length=10, verbose_name='Время добавления')),
                ('notes', models.TextField(verbose_name='Заметки для места ')),
            ],
            options={
                'verbose_name': 'Весенняя локация',
                'verbose_name_plural': 'Весении локации',
            },
        ),
        migrations.CreateModel(
            name='summer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Место')),
                ('time', models.CharField(max_length=10, verbose_name='Время добавления')),
                ('notes', models.TextField(verbose_name='Заметки для места ')),
            ],
            options={
                'verbose_name': 'Летняя локация',
                'verbose_name_plural': 'Летнии локации',
            },
        ),
        migrations.CreateModel(
            name='winter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Место')),
                ('time', models.CharField(max_length=10, verbose_name='Время добавления')),
                ('notes', models.TextField(verbose_name='Заметки для места ')),
            ],
            options={
                'verbose_name': 'Зимняя локация',
                'verbose_name_plural': 'Зимнии локации',
            },
        ),
    ]
