# Generated by Django 3.2.4 on 2021-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20210621_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='autem',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='autem',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='autem',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
