# Generated by Django 3.2.4 on 2021-06-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20210621_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='spring',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Главная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spring',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AddField(
            model_name='spring',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AddField(
            model_name='spring',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 3'),
        ),
        migrations.AddField(
            model_name='spring',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 4'),
        ),
        migrations.AddField(
            model_name='summer',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Главная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summer',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AddField(
            model_name='summer',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AddField(
            model_name='summer',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 3'),
        ),
        migrations.AddField(
            model_name='summer',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 4'),
        ),
        migrations.AddField(
            model_name='winter',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Главная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winter',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AddField(
            model_name='winter',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AddField(
            model_name='winter',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 3'),
        ),
        migrations.AddField(
            model_name='winter',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 4'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 3'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото номер 4'),
        ),
    ]
