# Generated by Django 3.2.4 on 2021-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20210621_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='autem',
            name='notes_fun',
            field=models.TextField(default=1, verbose_name='Заметки для развлечений '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autem',
            name='notes_nature',
            field=models.TextField(default=1, verbose_name='Заметки для природы '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autem',
            name='notes_ways',
            field=models.TextField(default=1, verbose_name='Заметки для маршрутов '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spring',
            name='notes_fun',
            field=models.TextField(default=1, verbose_name='Заметки для развлечений '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spring',
            name='notes_nature',
            field=models.TextField(default=1, verbose_name='Заметки для природы '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spring',
            name='notes_ways',
            field=models.TextField(default=1, verbose_name='Заметки для маршрутов '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summer',
            name='notes_fun',
            field=models.TextField(default=1, verbose_name='Заметки для развлечений '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summer',
            name='notes_nature',
            field=models.TextField(default=1, verbose_name='Заметки для природы '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summer',
            name='notes_ways',
            field=models.TextField(default=1, verbose_name='Заметки для маршрутов '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winter',
            name='notes_fun',
            field=models.TextField(default=1, verbose_name='Заметки для развлечений '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winter',
            name='notes_nature',
            field=models.TextField(default=1, verbose_name='Заметки для природы '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winter',
            name='notes_ways',
            field=models.TextField(default=1, verbose_name='Заметки для маршрутов '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autem',
            name='notes',
            field=models.TextField(verbose_name='Заметки для описания '),
        ),
        migrations.AlterField(
            model_name='spring',
            name='notes',
            field=models.TextField(verbose_name='Заметки для описания '),
        ),
        migrations.AlterField(
            model_name='summer',
            name='notes',
            field=models.TextField(verbose_name='Заметки для описания '),
        ),
        migrations.AlterField(
            model_name='winter',
            name='notes',
            field=models.TextField(verbose_name='Заметки для описания '),
        ),
    ]
