# Generated by Django 3.2.4 on 2021-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20210622_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autem',
            name='image1',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AlterField(
            model_name='autem',
            name='image2',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AlterField(
            model_name='spring',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AlterField(
            model_name='spring',
            name='image2',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AlterField(
            model_name='summer',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AlterField(
            model_name='summer',
            name='image2',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 2'),
        ),
        migrations.AlterField(
            model_name='winter',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 1'),
        ),
        migrations.AlterField(
            model_name='winter',
            name='image2',
            field=models.ImageField(upload_to='', verbose_name='Фото номер 2'),
        ),
    ]
